# Generated by Django 5.2 on 2025-10-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngos', '0003_campaignupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngodonation',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
