# Generated by Django 5.2 on 2025-10-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngos', '0004_ngodonation_is_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngoprofile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
