# Generated by Django 5.2.6 on 2025-10-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngos', '0005_ngoprofile_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngodonation',
            name='payment_method',
            field=models.CharField(blank=True, default='SSLCommerz', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ngodonation',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='ngodonation',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
