# Generated by Django 5.2.6 on 2025-10-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngos', '0006_ngodonation_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngodonation',
            name='account_input',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ngodonation',
            name='payer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
