# Generated by Django 5.2.6 on 2025-09-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('donor/recipient', 'Donor/Recipient'), ('ngo', 'NGO'), ('admin', 'Admin')], max_length=20, null=True),
        ),
    ]
