# Generated by Django 5.2.6 on 2025-09-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngoprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='askfordonation',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='askfordonation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='donateitem',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Campaign',
        ),
        migrations.DeleteModel(
            name='NGOProfile',
        ),
    ]
