# Generated by Django 5.2.6 on 2025-09-20 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_category_donationitem_donationimage_donationclaim_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='donationreview',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='donationreview',
            name='is_approved',
        ),
    ]
