# Generated by Django 5.2 on 2025-09-21 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_alter_donationreview_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='askfordonation',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donations.category'),
        ),
        migrations.AddField(
            model_name='askfordonation',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='askfordonation',
            name='delivery_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='askfordonation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ask_for_donations/'),
        ),
        migrations.AddField(
            model_name='askfordonation',
            name='needed_before',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='askfordonation',
            name='notify_immediately',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='askfordonation',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
