# Generated by Django 5.2 on 2025-09-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_requestitem_delete_askfordonation'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='urgency',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', help_text='Set the urgency of this request.', max_length=6),
        ),
    ]
