# Generated by Django 5.2 on 2025-09-23 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0009_requestitem_urgency'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationToRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='donations_to_request/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations_to_requests', to=settings.AUTH_USER_MODEL)),
                ('request_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donations.requestitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
